# This workflow will deploy BPMN digram to Camunda Process engine whenever a code is push to development branch


name: BPMN-Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "development" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: HTTP Request Action
        run : curl https://reqres.in/api/users?page=2
        
      - name: Upload Files
        run: |
              curl "https://api.upload.io/v2/accounts/FW25bCu/uploads/form_data" \
                   -H "Authorization: ${{CE_SECRET}}" \
                   -F file=@src/main/resource/process.bpmn
        
