# This workflow will deploy BPMN digram to Camunda Process engine whenever a code is push to development branch


name: BPMN-Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "development" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: HTTP Request Action
        run : curl https://reqres.in/api/users?page=2
        
      - name: Camunda Deploy BPMN
  # You may pin to the exact commit or the version.
  # uses: amardeep2006/camunda-deploy-bpmn-action@ed59544ae258d7512bede319baf022c4f5a373d0
      - uses: amardeep2006/camunda-deploy-bpmn-action@v1
        with:
          # Camunda api end point url
          CAMUNDA_ENDPOINT_URL: http://localhost:8080/engine-rest/deployment/create
          # Api user name for basic auth
          CAMUNDA_AUTH_USERNAME: demo
          # Password for api user for basic auth
          CAMUNDA_AUTH_PASSWORD: demo
