# This workflow will deploy BPMN digram to Camunda Process engine whenever a code is push to development branch


name: BPMN-Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "development" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: HTTP Request Action
        run : |
               curl "http://localhost:8080/engine-rest/version" ^
                -H "Accept-Language: en-US" ^
                -H "Connection: keep-alive" ^
                -H "Sec-Fetch-Dest: empty" ^
                -H "Sec-Fetch-Mode: cors" ^
                -H "Sec-Fetch-Site: cross-site" ^
                -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) CamundaModeler/5.8.0 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36" ^
                -H "accept: application/json" ^
                -H "authorization: undefined" ^
                -H "sec-ch-ua: ^\^"Not?A_Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"108^\^"" ^
                -H "sec-ch-ua-mobile: ?0" ^
                -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
                --compressed

